jqwidgets/demos/asp.net-core-mvc-tag-helpers/Controllers/TagHelpersController.cs
using System.Linq;
using jQWidgets.AspNet.Core.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;
using jQWidgets.AspNetCore.Mvc.TagHelpers;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http.Internal;

namespace jQWidgets.AspNet.Core.Controllers
{
    public class JSONData
    {
        public List<SalesEmployee> Employees
        {
            get;
            set;
        }
        public int TotalRecords
        {
            get;
            set;
        }
    }
    public class TagHelpersController : Controller
    {
        private jQWidgetsDemosContext _context;
        public TagHelpersController(jQWidgetsDemosContext context)
        {
            _context = context;
        }
        //
        // GET: /Widgets/
        public ActionResult Index()
        {
            return View("ScrollView/ScrollView");

            return View("ScrollView/ScrollView", _context.SalesEmployees);
        //    return View("DataTable/DataTableRowDetails", _context.Employee.ToList());
        }
        [HttpPost]
        public FileContentResult ExportData(FormPostBack data)
        { 
             return ExportHelper.ExportData(data);
        }

        [HttpPost]
        public string GetEmployees()
        {
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList(); 
            JSONData data = new JSONData();
            data.TotalRecords = allEmployees.Count;
            data.Employees = allEmployees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetChildren(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);
            string id = (string)token.SelectToken("ID");
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            JSONData data = new JSONData();
            List<SalesEmployee> employees = new List<SalesEmployee>();
            for (int i = 0; i < allEmployees.Count; i++)
            {
                if (String.IsNullOrEmpty(id))
                {
                    if (i < 5)
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
                else
                {
                    if (allEmployees[i].ReportsTo == Int32.Parse(id))
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
            }
            data.TotalRecords = allEmployees.Count;
            data.Employees = employees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetPageData(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);

            List<JToken> filterGroups = token.SelectToken("filterGroups").Children().ToList();
            int pageSize = (int)token.SelectToken("pagesize");
            int pageNum = (int)token.SelectToken("pagenum");
            string sortField = (string)token.SelectToken("sortdatafield");
            string sortOrder = (string)token.SelectToken("sortorder");
            int count = 0;
            List<SalesEmployee> employees = new List<SalesEmployee>();
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            if (sortField != "")
            {
                if (sortOrder == "asc")
                {              
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p))
                                 select p).ToList();

                }
                else if (sortOrder == "desc")
                {
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p)) descending
                                    select p).ToList();
                }
            }
            if (filterGroups.Count > 0)
            {
                List<SalesEmployee> filteredEmployees = allEmployees;
                for (int j = 0; j < filterGroups.Count; j++)
                {
                    List<JToken> filters = filterGroups[j].SelectToken("filters").Children().ToList();

                    List<SalesEmployee> filterGroup = filteredEmployees;
                    List<SalesEmployee> filterGroupResult = new List<SalesEmployee>();
                    for (int i = 0; i < filters.Count; i++)
                    {
                        string filterLabel = (string)filters[i].SelectToken("label");
                        string filterValue = (string)filters[i].SelectToken("value");
                        string filterDataField = (string)filters[i].SelectToken("field");
                        string filterCondition = (string)filters[i].SelectToken("condition");
                        string filterType = (string)filters[i].SelectToken("type");
                        string filterOperator = (string)filters[i].SelectToken("operator");

                        List<SalesEmployee> currentResult = new List<SalesEmployee>();

                        switch (filterCondition)
                        {
                            case "NOT_EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) != null)
                                                     select p).ToList();
                                break;
                            case "NOT_NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != "")
                                                     select p).ToList();
                                break;
                            case "NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) == null)
                                                     select p).ToList();
                                break;
                            case "EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == "")
                                                     select p).ToList();
                                break;
                            case "CONTAINS_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "CONTAINS":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != -1)
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where (!(p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == -1)
                                                     select p).ToList();
                                break;
                            case "EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == filterValue)
                                                     select p).ToList();
                                break;
                            case "EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == 0)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != filterValue)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != 0)

jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/DataTable/DataTable.cshtml
@model IEnumerable<jQWidgets.AspNet.Core.Models.Employee>

@{
    ViewData["Title"] = "ASP .NET MVC DataTable Example";
}
<label>ASP .NET Core MVC DataTable Tag Helper Example</label><br/><br/>
<jqx-datatable theme="@ViewData["Theme"]" sortable="true" width="850" source="Model"> 
    <jqx-datatable-columns>
        <jqx-datatable-column columngroup="name" dataField="FirstName" width="100" text="First Name"></jqx-datatable-column>
        <jqx-datatable-column columngroup="name" dataField="LastName" width="100" text="Last Name"></jqx-datatable-column>
        <jqx-datatable-column dataField="Title" width="150"></jqx-datatable-column>
        <jqx-datatable-column dataField="Address" width="200"></jqx-datatable-column>
        <jqx-datatable-column dataField="City" width="150"></jqx-datatable-column>
        <jqx-datatable-column dataField="Country"></jqx-datatable-column>
    </jqx-datatable-columns>
    <jqx-datatable-column-groups>
        <jqx-datatable-column-group name="name" text="Name"></jqx-datatable-column-group>
    </jqx-datatable-column-groups>
</jqx-datatable>


jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/DataTable/DataTableFiltering.cshtml
@model IEnumerable<jQWidgets.AspNet.Core.Models.SalesEmployee>
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC DataTable Filtering Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<label>ASP .NET Core MVC DataTable Filtering Example</label><br/><br/>
<jqx-datatable id="dataTable" altrows="true" filterable="true" pageable="true" sourceId="@employee.ID" theme="@ViewData["Theme"]" sortable="true" width="850" source="Model">
    <jqx-datatable-columns>
        <jqx-datatable-column dataField-for="@(employee.FirstName)" width="150" text="First Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.LastName)" width="150" text="Last Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.ProductName)" width="250" text="Product Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Price)" width="100" text="Price" cellsFormat="c2" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Quantity)" width="100" text="Quantity" cellsAlign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Total)" width="100" text="Total" cellsFormat="c2" cellsAlign="HorizontalAlignment.Right"></jqx-datatable-column>
 </jqx-datatable-columns>
</jqx-datatable>

jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/DataTable/DataTableRowDetails.cshtml
@model IEnumerable<jQWidgets.AspNet.Core.Models.SalesEmployee>
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC DataTable Row Details Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<script>
    var initRowDetails = function (id, record, element, rowinfo) {
        var id = id.toString();
        
        var grid = element;

        var data = [];

        var generaterow = function (i) {
            var row = {};      
            row["OrderDate"] = new Date(2016, Math.floor(Math.random() * 11), Math.floor(Math.random() * 27))
            row["Quantity"] = Math.floor(Math.random() * 50)
            row["ProductName"] = record.ProductName;
            return row;
        }

        for (var i = 0; i < Math.max(10, Math.floor(Math.random() * 20)) ; i++) {
            var row = generaterow(i);
            data[i] = row;
        }

        var source = {
            datafields: [
                { name: 'OrderDate', type: 'date' },
                { name: 'Quantity', type: 'string' },
                { name: 'ProductName', type: 'string' }
            ],
            localdata: data
        }
        var nestedGridAdapter = new $.jqx.dataAdapter(source);
        if (grid != null) {
            grid.jqxDataTable({
                source: nestedGridAdapter, width: 780, height: 200,
                columns: [
                  { text: 'Order Date', cellsformat:'d', dataField: 'OrderDate', width: 200 },
                  { text: 'Quantity', cellsalign:'right', dataField: 'Quantity', width: 200 },
                  { text: 'Product Name', dataField: 'ProductName' }
                ]
            });
        }
    }
</script>
<label>ASP .NET Core MVC DataTable Row Details Example</label><br/><br/>
<jqx-datatable id="grid" altRows="true" rowDetails="true" pageable="true" initRowDetails="initRowDetails()" sourceId="@(employee.ID)" theme="@ViewData["Theme"]" sortable="true" width="790" source="Model">
    <jqx-datatable-columns>
        <jqx-datatable-column dataField-for="@(employee.FirstName)" width="150" text="First Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.LastName)" width="150" text="Last Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.ProductName)" width="200" text="Product Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Price)" width="100" text="Price" cellsformat="c2" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Quantity)" width="100" text="Quantity" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Total)" text="Total" cellsformat="c2" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
 </jqx-datatable-columns>
</jqx-datatable>

jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/DataTable/DataTableServerPaging.cshtml
@model IEnumerable<jQWidgets.AspNet.Core.Models.SalesEmployee>
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC DataTable Server Paging, Sorting and Filtering Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<label>ASP .NET Core MVC DataTable Server Paging Example</label><br/><br/>
<jqx-datatable id="grid" serverProcessing="true" altrows="true" filterable="true" pageable="true" sourceId="@(employee.ID)" theme="@ViewData["Theme"]" sortable="true" width="850" sourceRoot="Employees" sourceTotalRecords="TotalRecords" sourceUrl="@Url.Action("GetPageData","TagHelpers")" sourceModel="@employee">
    <jqx-datatable-columns>
        <jqx-datatable-column dataField-for="@(employee.FirstName)" width="150" text="First Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.LastName)" width="150" text="Last Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.ProductName)" width="250" text="Product Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Price)" width="100" text="Price" cellsformat="c2" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Quantity)" width="100" text="Quantity" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Total)" width="100" text="Total" cellsformat="c2" cellsalign="HorizontalAlignment.Right"></jqx-datatable-column>
 </jqx-datatable-columns>
</jqx-datatable>

jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/DataTable/DataTableSorting.cshtml
@model IEnumerable<jQWidgets.AspNet.Core.Models.Employee>

@{
    ViewData["Title"] = "ASP .NET MVC DataTable Sorting Example";
}
@{
    var employee = Model.FirstOrDefault();
}
<label>ASP .NET Core MVC DataTable Sorting Example</label><br/><br/>
<jqx-datatable theme="@ViewData["Theme"]" sortable="true" width="850" source="Model"> 
    <jqx-datatable-columns>
        <jqx-datatable-column columngroup="name" dataField-for="@(employee.FirstName)" width="100" text="First Name"></jqx-datatable-column>
        <jqx-datatable-column columngroup="name" dataField-for="@(employee.LastName)" width="100" text="Last Name"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Title)" width="150"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Address)" width="200"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.City)" width="150"></jqx-datatable-column>
        <jqx-datatable-column dataField-for="@(employee.Country)"></jqx-datatable-column>
    </jqx-datatable-columns>
    <jqx-datatable-column-groups>
        <jqx-datatable-column-group name="name" text="Name"></jqx-datatable-column-group>
    </jqx-datatable-column-groups>
</jqx-datatable>
